# certs mounting points in the container(s)
tls:
  certificates:
    - certFile: /etc/traefik/certs/localhost-cert.pem
      keyFile: /etc/traefik/certs/localhost-key.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/localhost-cert.pem
        keyFile: /etc/traefik/certs/localhost-key.pem

# middleware
http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        port: "8443" # doc: see https://doc.traefik.io/traefik/middlewares/http/redirectscheme/
        permanent: true
